In [10]:
import zipfile
import pandas as pd
import os
import re

In [11]:
# dict for columns
data = {'filename': [], 'place': [], 'year': []}

In [12]:
# for each file in new_elections
for zip in os.listdir('new_elections/dataverse'):
    zip_ref= zipfile.ZipFile('new_elections/dataverse/' + zip)

    files = zip_ref.namelist()

    # for each file in the zip
    for file in files:
        if file == 'Minneapolis 2013-board of estimation and taxation cvr.csv':
            city = 'Minneapolis'
            year = '2013'
        else:
            # remove .csv and tokenize
            tokens = file.replace('.csv', '').split('_')
            # add spaces before capital letters in city
            city = re.sub(r"\B([A-Z])", r" \1", tokens[0])
            year = tokens[1][-4:]
        # add to dict
        data['filename'].append(file)
        data['place'].append(city)
        data['year'].append(year)

    zip_ref.close()

In [13]:
# convert data to df
df = pd.DataFrame(data)
df

                                              filename          place  year
0               Cambridge_11082005_SchoolCommittee.csv      Cambridge  2005
1               Cambridge_11032015_SchoolCommittee.csv      Cambridge  2015
2               Cambridge_11042003_SchoolCommittee.csv      Cambridge  2003
3               Cambridge_11152019_SchoolCommittee.csv      Cambridge  2019
4                   Cambridge_11152019_CityCouncil.csv      Cambridge  2019
..                                                 ...            ...   ...
496  SanFrancisco_11082016_BoardofSupervisorsDistri...  San Francisco  2016
497  Burlington_03072023_CityCouncilCentralDistrict...     Burlington  2023
498                Alaska_11082022_SenateDistrictK.csv         Alaska  2022
499                    SanFrancisco_11062007_Mayor.csv  San Francisco  2007
500     SanFrancisco_11082022_BoardofSupervisorsD6.csv  San Francisco  2022

[501 rows x 3 columns]

In [14]:
# save as dataverse.csv in new_elections folder
# df.to_csv('new_elections/dataverse.csv', index=False)

In [21]:
# open elections.xlsx
elections = pd.read_excel('elections.xlsx')
elections

,filename,city,state,Geography,District #,office,year,geo_filename
0,NewYorkCity_06222021_DEMBoroughPresidentBronx.csv,New York,NY,boroughcounty,Bronx,Borough president,2021,NaN
1,NewYorkCity_06222021_DEMBoroughPresidentKings.csv,New York,NY,boroughcounty,Kings,Borough president,2021,NaN
2,NewYorkCity_06222021_DEMBoroughPresidentNewYor...,New York,NY,boroughcounty,New York,Borough president,2021,NaN
3,NewYorkCity_06222021_DEMBoroughPresidentQueens...,New York,NY,boroughcounty,Queens,Borough president,2021,NaN
4,NewYorkCity_06222021_DEMBoroughPresidentRichmo...,New York,NY,boroughcounty,Richmond,Borough president,2021,NaN
...,...,...,...,...,...,...,...,...
404,Alaska_11082022_SenateDistrictP.csv,NaN,AK,upper state legislative,P,State senate,2022,alaska_upper_districts_2022.csv
405,Alaska_11082022_SenateDistrictQ.csv,NaN,AK,upper state legislative,Q,State senate,2022,alaska_upper_districts_2022.csv
406,Alaska_11082022_SenateDistrictR.csv,NaN,AK,upper state legislative,R,State senate,2022,alaska_upper_districts_2022.csv
407,Alaska_11082022_SenateDistrictS.csv,NaN,AK,upper state legislative,S,State senate,2022,alaska_upper_districts_2022.csv
408,Maine_07142020_DemocraticCandidateforMaineStat...,NaN,ME,upper state legislative,11,State Senate,2020,maine_upper_districts_2020.csv

In [23]:
# get all filenames that are in dataverse but not in elections
missing = df[~df['filename'].isin(elections['filename'])]
missing

                                           filename          place  year
0            Cambridge_11082005_SchoolCommittee.csv      Cambridge  2005
1            Cambridge_11032015_SchoolCommittee.csv      Cambridge  2015
2            Cambridge_11042003_SchoolCommittee.csv      Cambridge  2003
3            Cambridge_11152019_SchoolCommittee.csv      Cambridge  2019
4                Cambridge_11152019_CityCouncil.csv      Cambridge  2019
..                                              ...            ...   ...
433      Minneapolis_11072023_CityCouncilWard10.csv    Minneapolis  2023
441      Portland_06142022_Schoolboarddistrict5.csv       Portland  2022
477  SanLeandro_11082016_CountyCouncilDistrict6.csv    San Leandro  2016
483             SanFrancisco_11052019_Treasurer.csv  San Francisco  2019
488        Minnetonka_11072023_CityCouncilWard1.csv     Minnetonka  2023

[90 rows x 3 columns]

In [25]:
# save missing as missing.csv in new_elections folder
missing.to_csv('new_elections/missing.csv', index=False)

In [26]:
# get all filenames that are in elections but not in dataverse
extra = elections[~elections['filename'].isin(df['filename'])]
extra

Empty DataFrame
Columns: [filename, city, state, Geography, District #, office, year, geo_filename]
Index: []